Update eventmachine and activesupport.
I ran into some issues doing both `bundle install` and `bundle exec
middleman build` locally. I couldn't build the C extensions for
eventmachine on the Gemfile.lock'd version. Upgrading the patch version
to the latests 1.0.7 eventually worked for me. Secondly, activesupport
complained when trying to parse a date in lib/monkeypatch_blog_date:

.../ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/values/time_zone.rb:290:in
`parse': undefined method `year' for nil:NilClass (NoMethodError)

Upgrading to latests activesupport fixed my issue.